### ISSUE TITLE
support non-JPG images

### ISSUE THREAD

**Issue by ruckc** [tw-yshuang/coco2yolo#8]
Currently coco2yolo only functions with .jpg images.  Ideally support a parameter that allows choosing another extension (PNG, GIF).

**Comment by johnning2333** [comment]
indeed

**Comment by tw-yshuang** [comment]
Hi, I released [v1.1.0](https://github.com/tw-yshuang/coco2yolo/releases/tag/v1.1.0), a new feature that followed your advice.
Now it already supports `jpg`, `png`, `gif`.
Hope you enjoy it! 🎉🎉
